FROM openjdk:8-jdk-alpine

ENV JACAMO_HOME=/jacamo/build
ENV PATH $PATH:$JAVA_HOME/bin:$JACAMO_HOME/scripts

RUN apk add --update --no-cache git bash fontconfig ttf-dejavu graphviz
RUN git clone https://github.com/jacamo-lang/jacamo.git && \
    cd jacamo && \
    git checkout tags/v1.0 && \
    ./gradlew config

# COPY src src/
# WORKDIR src

# ISSO AQUI FUNCIONA NO DOCKER-COMPOSE, TENTANDO TIRAR PRA ADAPTAR NO SISTEMA
# ENTRYPOINT ["/bin/bash", "jacamo", "/src/juntando_jason_jacamo.jcm"]



#jacamo /src/helloworld.jcm

#EXPOSE 3271
#EXPOSE 3272
#EXPOSE 3273
#EXPOSE 8080
#EXPOSE 8081

#ENTRYPOINT [ "/bin/bash" ]
#CMD []